version: "3"
services:
  # next_app:
  #   build: ./front
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - flask_app
        # - ./back:/app

  flask_app:
    build: ./back
    ports:
      - "5000:5000"
    depends_on:
      - db
    tty: true
    stdin_open: true  

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quotesdb
      POSTGRES_USER: quotes
      POSTGRES_PASSWORD: quotes
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./back:/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    depends_on:
      - db

volumes:
  postgres_data:
