FROM node:18

# アプリケーションの作業ディレクトリを設定
WORKDIR /usr/src/app

# package.jsonとpackage-lock.jsonをコピー
COPY package*.json ./
# COPY package-lock.json .

# 依存関係をインストール
RUN npm install --save-dev @firebase/app @firebase/auth @firebase/analytics @types/firebase

# Firebase Toolsのインストール
RUN npm install -g firebase-tools

# Firebase SDKのインストール
RUN npm install firebase

# JestとReact Testing LibraryとBabelとts-jestとjest-environment-jsdomをインストール
RUN npm install --save-dev jest @testing-library/react @testing-library/jest-dom
RUN npm install --save-dev @babel/core @babel/preset-env @babel/preset-react @babel/preset-typescript
RUN npm install --save-dev ts-jest@
RUN npm install --save-dev jest-environment-jsdom
# ソースコードをコピー
COPY . .

# アプリケーションをビルド
# RUN npm run build

# アプリケーションが使用するポートを公開
EXPOSE 3000

# アプリケーションを実行
# CMD ["npm", "start"]
CMD ["npm", "run", "dev"]
